services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=empenio_secret_key_2025
    networks:
      - empenio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    networks:
      - empenio_network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  # Módulo IA (Python)
  ia_module:
    build:
      context: .
      dockerfile: Dockerfile.ia
    ports:
      - "5001:5001"
    networks:
      - empenio_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  empenio_network:
    driver: bridge
